@ProductProcessing_HostAddress = http://localhost:5000

# Get all products
GET {{ProductProcessing_HostAddress}}/api/products
Accept: application/json

###

# Get product by ID
GET {{ProductProcessing_HostAddress}}/api/products/1
Accept: application/json

###

# Create a new product
POST {{ProductProcessing_HostAddress}}/api/products
Content-Type: application/json

{
  "name": "Test Product",
  "description": "A test product",
  "price": 100.00,
  "stock": 10
}

###

# Update a product
PUT {{ProductProcessing_HostAddress}}/api/products/1
Content-Type: application/json

{
  "name": "Updated Product",
  "description": "An updated product",
  "price": 150.00,
  "stock": 15
}

###

# Calculate discount
GET {{ProductProcessing_HostAddress}}/api/products/1/discount?percentage=10
Accept: application/json

###

# Delete a product
DELETE {{ProductProcessing_HostAddress}}/api/products/1

###

